0.0.0 - Màj auto

diff --git a/gtm/gtminstall b/gtm/gtminstall
--- a/gtm/gtminstall
+++ b/gtm/gtminstall
@@ -422,49 +422,49 @@ if [ -d "$gtm_installdir" -a "Y" != "$gtm_overwrite_existing" ] ; then
     echo $gtm_installdir exists and --overwrite-existing not specified ; err_exit
 fi
 
-issystemd=`which systemctl`
-if [ "" != "$issystemd" ] ; then
-	# It is a systemd installation
-	logindconf="/etc/systemd/logind.conf"
-	removeipcopt=`awk -F = '/^RemoveIPC/ {opt=$2} END{print opt}' $logindconf`
-	if [ "no" != "$removeipcopt" ] ; then
-		# RemoveIPC=no is NOT the final settings in the file
-		ipcissue1="If RemoveIPC=yes is configured for systemd, ipcs (database shm & sem)"
-		ipcissue1="$ipcissue1 are removed for a non-system user's processes when that user logs out."
-		ipcissue2="That can cause database operations to fail with mysterious errors."
+# issystemd=`which systemctl`
+# if [ "" != "$issystemd" ] ; then
+# 	# It is a systemd installation
+# 	logindconf="/etc/systemd/logind.conf"
+# 	removeipcopt=`awk -F = '/^RemoveIPC/ {opt=$2} END{print opt}' $logindconf`
+# 	if [ "no" != "$removeipcopt" ] ; then
+# 		# RemoveIPC=no is NOT the final settings in the file
+# 		ipcissue1="If RemoveIPC=yes is configured for systemd, ipcs (database shm & sem)"
+# 		ipcissue1="$ipcissue1 are removed for a non-system user's processes when that user logs out."
+# 		ipcissue2="That can cause database operations to fail with mysterious errors."
 
-		ipcline1="# GT.M : Override systemd default of RemoveIPC=yes to prevent automatic ipc removal of"
-		ipcline1="$ipcline1 Shared Memory Segments and Semaphore Arrays of orphaned databases"
-		ipcline2="RemoveIPC=no"
-		ipccmd="systemctl restart systemd-logind"
+# 		ipcline1="# GT.M : Override systemd default of RemoveIPC=yes to prevent automatic ipc removal of"
+# 		ipcline1="$ipcline1 Shared Memory Segments and Semaphore Arrays of orphaned databases"
+# 		ipcline2="RemoveIPC=no"
+# 		ipccmd="systemctl restart systemd-logind"
 
-		echo "$ipcissue1"
-		echo "$ipcissue2"
-		echo "The installation would like to add the below two lines to $logindconf"
-		echo "   $ipcline1"
-		echo "   $ipcline2"
-		echo "And issue the below command to restart systemd-logind"
-		echo "   $ipccmd"
-		echo -n "Do you wish to proceed (Y/N)? "
-		answer=`read_yes_no`
-		if [ "yes" != "$answer" ] ; then
-			echo "Will abort installation"
-			echo $ipcissue1
-			echo $ipcissue2
-			echo "Please add the below two lines to $logindconf"
-			echo "   $ipcline1"
-			echo "   $ipcline2"
-			echo "and restart systemd-logind using the below command, for example or by rebooting the system"
-			echo "   $ipccmd"
-			echo "and retry GT.M installation"
-			exit 1
-		fi
-		echo $ipcline1 >> $logindconf
-		echo $ipcline2 >> $logindconf
-		$ipccmd
-	fi
-fi
-if [ "Y" = "$gtm_verbose" ] ; then echo Finished checking options and assigning defaults ; dump_info ; fi
+# 		echo "$ipcissue1"
+# 		echo "$ipcissue2"
+# 		echo "The installation would like to add the below two lines to $logindconf"
+# 		echo "   $ipcline1"
+# 		echo "   $ipcline2"
+# 		echo "And issue the below command to restart systemd-logind"
+# 		echo "   $ipccmd"
+# 		echo -n "Do you wish to proceed (Y/N)? "
+# 		answer=`read_yes_no`
+# 		if [ "yes" != "$answer" ] ; then
+# 			echo "Will abort installation"
+# 			echo $ipcissue1
+# 			echo $ipcissue2
+# 			echo "Please add the below two lines to $logindconf"
+# 			echo "   $ipcline1"
+# 			echo "   $ipcline2"
+# 			echo "and restart systemd-logind using the below command, for example or by rebooting the system"
+# 			echo "   $ipccmd"
+# 			echo "and retry GT.M installation"
+# 			exit 1
+# 		fi
+# 		echo $ipcline1 >> $logindconf
+# 		echo $ipcline2 >> $logindconf
+# 		$ipccmd
+# 	fi
+# fi
+# if [ "Y" = "$gtm_verbose" ] ; then echo Finished checking options and assigning defaults ; dump_info ; fi
 
 # Prepare input to GT.M configure script
 gtm_configure_in=${gtm_tmp}/configure_${timestamp}.in
@@ -515,7 +515,6 @@ chmod +x configure.sh
 if [ "Y" = "$gtm_dryrun" ] ; then echo Installation prepared in $gtm_tmp ; exit ; fi
 
 # Correction bug pour utiliser Docker (0.14B)
-echo Y >>$gtm_configure_in # réponse à : Do you wish to proceed (Y/N)?
 sed -i 's|"`./geteuid`" != "root"|$EUID != 0|' ./configure.sh
 
 ./configure.sh <$gtm_configure_in 1> $gtm_tmp/configure_${timestamp}.out 2>$gtm_tmp/configure_${timestamp}.err
